/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const FoodRequest = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'fulfilled' : IDL.Null,
    'open' : IDL.Null,
  }),
  'urgency' : IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'critical' : IDL.Null,
    'medium' : IDL.Null,
  }),
  'createdAt' : Time,
  'unit' : IDL.Variant({
    'kg' : IDL.Null,
    'pieces' : IDL.Null,
    'litres' : IDL.Null,
  }),
  'numberOfPeople' : IDL.Nat,
  'ngoId' : IDL.Principal,
  'notes' : IDL.Text,
  'quantityNeeded' : IDL.Nat,
  'foodType' : IDL.Text,
});
export const FoodListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'expired' : IDL.Null,
    'completed' : IDL.Null,
    'claimed' : IDL.Null,
    'available' : IDL.Null,
  }),
  'expiresAt' : Time,
  'createdAt' : Time,
  'unit' : IDL.Variant({
    'kg' : IDL.Null,
    'pieces' : IDL.Null,
    'litres' : IDL.Null,
  }),
  'cookedAt' : Time,
  'ngoId' : IDL.Opt(IDL.Principal),
  'notes' : IDL.Text,
  'quantity' : IDL.Nat,
  'hostId' : IDL.Principal,
  'vegNonVeg' : IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null }),
  'foodName' : IDL.Text,
  'pickupLocation' : IDL.Text,
});
export const Role = IDL.Variant({
  'ngo' : IDL.Null,
  'admin' : IDL.Null,
  'host' : IDL.Null,
  'volunteer' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'isApproved' : IDL.Bool,
  'name' : IDL.Text,
  'joinedAt' : Time,
  'role' : Role,
  'organization' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const DeliveryStatus = IDL.Variant({
  'onTheWay' : IDL.Null,
  'pickedUp' : IDL.Null,
  'delivered' : IDL.Null,
  'accepted' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Delivery = IDL.Record({
  'id' : IDL.Nat,
  'status' : DeliveryStatus,
  'listingId' : IDL.Nat,
  'createdAt' : Time,
  'updatedAt' : Time,
  'volunteerId' : IDL.Principal,
  'ngoId' : IDL.Principal,
  'proofImage' : IDL.Opt(ExternalBlob),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'userId' : IDL.Principal,
  'createdAt' : Time,
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
});
export const PlatformStats = IDL.Record({
  'totalVolunteersActive' : IDL.Nat,
  'totalNgosServed' : IDL.Nat,
  'totalFoodSaved' : IDL.Nat,
  'totalDeliveriesCompleted' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptDelivery' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelFoodRequest' : IDL.Func([IDL.Nat], [], []),
  'cancelListing' : IDL.Func([IDL.Nat], [], []),
  'claimListing' : IDL.Func([IDL.Nat], [], []),
  'createFoodRequest' : IDL.Func([FoodRequest], [], []),
  'createListing' : IDL.Func([FoodListing], [], []),
  'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getAllDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
  'getAllRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
  'getAvailableListings' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(FoodListing)],
      ['query'],
    ),
  'getAvailableTasks' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
  'getMyListings' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
  'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getMyRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
  'getOpenRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
  'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleNgoApproval' : IDL.Func([IDL.Principal], [], []),
  'updateDeliveryStatus' : IDL.Func(
      [IDL.Nat, DeliveryStatus, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'updateListingStatus' : IDL.Func(
      [
        IDL.Nat,
        IDL.Variant({
          'expired' : IDL.Null,
          'completed' : IDL.Null,
          'claimed' : IDL.Null,
          'available' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const FoodRequest = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'fulfilled' : IDL.Null,
      'open' : IDL.Null,
    }),
    'urgency' : IDL.Variant({
      'low' : IDL.Null,
      'high' : IDL.Null,
      'critical' : IDL.Null,
      'medium' : IDL.Null,
    }),
    'createdAt' : Time,
    'unit' : IDL.Variant({
      'kg' : IDL.Null,
      'pieces' : IDL.Null,
      'litres' : IDL.Null,
    }),
    'numberOfPeople' : IDL.Nat,
    'ngoId' : IDL.Principal,
    'notes' : IDL.Text,
    'quantityNeeded' : IDL.Nat,
    'foodType' : IDL.Text,
  });
  const FoodListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'expired' : IDL.Null,
      'completed' : IDL.Null,
      'claimed' : IDL.Null,
      'available' : IDL.Null,
    }),
    'expiresAt' : Time,
    'createdAt' : Time,
    'unit' : IDL.Variant({
      'kg' : IDL.Null,
      'pieces' : IDL.Null,
      'litres' : IDL.Null,
    }),
    'cookedAt' : Time,
    'ngoId' : IDL.Opt(IDL.Principal),
    'notes' : IDL.Text,
    'quantity' : IDL.Nat,
    'hostId' : IDL.Principal,
    'vegNonVeg' : IDL.Variant({ 'veg' : IDL.Null, 'nonVeg' : IDL.Null }),
    'foodName' : IDL.Text,
    'pickupLocation' : IDL.Text,
  });
  const Role = IDL.Variant({
    'ngo' : IDL.Null,
    'admin' : IDL.Null,
    'host' : IDL.Null,
    'volunteer' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'isApproved' : IDL.Bool,
    'name' : IDL.Text,
    'joinedAt' : Time,
    'role' : Role,
    'organization' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const DeliveryStatus = IDL.Variant({
    'onTheWay' : IDL.Null,
    'pickedUp' : IDL.Null,
    'delivered' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Delivery = IDL.Record({
    'id' : IDL.Nat,
    'status' : DeliveryStatus,
    'listingId' : IDL.Nat,
    'createdAt' : Time,
    'updatedAt' : Time,
    'volunteerId' : IDL.Principal,
    'ngoId' : IDL.Principal,
    'proofImage' : IDL.Opt(ExternalBlob),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'userId' : IDL.Principal,
    'createdAt' : Time,
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
  });
  const PlatformStats = IDL.Record({
    'totalVolunteersActive' : IDL.Nat,
    'totalNgosServed' : IDL.Nat,
    'totalFoodSaved' : IDL.Nat,
    'totalDeliveriesCompleted' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptDelivery' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelFoodRequest' : IDL.Func([IDL.Nat], [], []),
    'cancelListing' : IDL.Func([IDL.Nat], [], []),
    'claimListing' : IDL.Func([IDL.Nat], [], []),
    'createFoodRequest' : IDL.Func([FoodRequest], [], []),
    'createListing' : IDL.Func([FoodListing], [], []),
    'createNotification' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getAllDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
    'getAllRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
    'getAvailableListings' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(FoodListing)],
        ['query'],
      ),
    'getAvailableTasks' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyDeliveries' : IDL.Func([], [IDL.Vec(Delivery)], ['query']),
    'getMyListings' : IDL.Func([], [IDL.Vec(FoodListing)], ['query']),
    'getMyNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getMyRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
    'getOpenRequests' : IDL.Func([], [IDL.Vec(FoodRequest)], ['query']),
    'getPlatformStats' : IDL.Func([], [PlatformStats], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'markNotificationAsRead' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleNgoApproval' : IDL.Func([IDL.Principal], [], []),
    'updateDeliveryStatus' : IDL.Func(
        [IDL.Nat, DeliveryStatus, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateListingStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({
            'expired' : IDL.Null,
            'completed' : IDL.Null,
            'claimed' : IDL.Null,
            'available' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };