/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Delivery {
  'id' : bigint,
  'status' : DeliveryStatus,
  'listingId' : bigint,
  'createdAt' : Time,
  'updatedAt' : Time,
  'volunteerId' : Principal,
  'ngoId' : Principal,
  'proofImage' : [] | [ExternalBlob],
}
export type DeliveryStatus = { 'onTheWay' : null } |
  { 'pickedUp' : null } |
  { 'delivered' : null } |
  { 'accepted' : null };
export type ExternalBlob = Uint8Array;
export interface FoodListing {
  'id' : bigint,
  'status' : { 'expired' : null } |
    { 'completed' : null } |
    { 'claimed' : null } |
    { 'available' : null },
  'expiresAt' : Time,
  'createdAt' : Time,
  'unit' : { 'kg' : null } |
    { 'pieces' : null } |
    { 'litres' : null },
  'cookedAt' : Time,
  'ngoId' : [] | [Principal],
  'notes' : string,
  'quantity' : bigint,
  'hostId' : Principal,
  'vegNonVeg' : { 'veg' : null } |
    { 'nonVeg' : null },
  'foodName' : string,
  'pickupLocation' : string,
}
export interface FoodRequest {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'fulfilled' : null } |
    { 'open' : null },
  'urgency' : { 'low' : null } |
    { 'high' : null } |
    { 'critical' : null } |
    { 'medium' : null },
  'createdAt' : Time,
  'unit' : { 'kg' : null } |
    { 'pieces' : null } |
    { 'litres' : null },
  'numberOfPeople' : bigint,
  'ngoId' : Principal,
  'notes' : string,
  'quantityNeeded' : bigint,
  'foodType' : string,
}
export interface Notification {
  'id' : bigint,
  'userId' : Principal,
  'createdAt' : Time,
  'isRead' : boolean,
  'message' : string,
}
export interface PlatformStats {
  'totalVolunteersActive' : bigint,
  'totalNgosServed' : bigint,
  'totalFoodSaved' : bigint,
  'totalDeliveriesCompleted' : bigint,
}
export type Role = { 'ngo' : null } |
  { 'admin' : null } |
  { 'host' : null } |
  { 'volunteer' : null };
export type Time = bigint;
export interface UserProfile {
  'id' : Principal,
  'isApproved' : boolean,
  'name' : string,
  'joinedAt' : Time,
  'role' : Role,
  'organization' : [] | [string],
  'phone' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptDelivery' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelFoodRequest' : ActorMethod<[bigint], undefined>,
  'cancelListing' : ActorMethod<[bigint], undefined>,
  'claimListing' : ActorMethod<[bigint], undefined>,
  'createFoodRequest' : ActorMethod<[FoodRequest], undefined>,
  'createListing' : ActorMethod<[FoodListing], undefined>,
  'createNotification' : ActorMethod<[Principal, string], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'getAllDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getAllListings' : ActorMethod<[], Array<FoodListing>>,
  'getAllRequests' : ActorMethod<[], Array<FoodRequest>>,
  'getAvailableListings' : ActorMethod<[bigint, bigint], Array<FoodListing>>,
  'getAvailableTasks' : ActorMethod<[], Array<FoodListing>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyDeliveries' : ActorMethod<[], Array<Delivery>>,
  'getMyListings' : ActorMethod<[], Array<FoodListing>>,
  'getMyNotifications' : ActorMethod<[], Array<Notification>>,
  'getMyRequests' : ActorMethod<[], Array<FoodRequest>>,
  'getOpenRequests' : ActorMethod<[], Array<FoodRequest>>,
  'getPlatformStats' : ActorMethod<[], PlatformStats>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'markNotificationAsRead' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleNgoApproval' : ActorMethod<[Principal], undefined>,
  'updateDeliveryStatus' : ActorMethod<
    [bigint, DeliveryStatus, [] | [ExternalBlob]],
    undefined
  >,
  'updateListingStatus' : ActorMethod<
    [
      bigint,
      { 'expired' : null } |
        { 'completed' : null } |
        { 'claimed' : null } |
        { 'available' : null },
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];