/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface FoodListing {
    id: bigint;
    status: Variant_expired_completed_claimed_available;
    expiresAt: Time;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    cookedAt: Time;
    ngoId?: Principal;
    notes: string;
    quantity: bigint;
    hostId: Principal;
    vegNonVeg: Variant_veg_nonVeg;
    foodName: string;
    pickupLocation: string;
}
export interface Notification {
    id: bigint;
    userId: Principal;
    createdAt: Time;
    isRead: boolean;
    message: string;
}
export interface Delivery {
    id: bigint;
    status: DeliveryStatus;
    listingId: bigint;
    createdAt: Time;
    updatedAt: Time;
    volunteerId: Principal;
    ngoId: Principal;
    proofImage?: ExternalBlob;
}
export interface PlatformStats {
    totalVolunteersActive: bigint;
    totalNgosServed: bigint;
    totalFoodSaved: bigint;
    totalDeliveriesCompleted: bigint;
}
export interface FoodRequest {
    id: bigint;
    status: Variant_cancelled_fulfilled_open;
    urgency: Variant_low_high_critical_medium;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    numberOfPeople: bigint;
    ngoId: Principal;
    notes: string;
    quantityNeeded: bigint;
    foodType: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    id: Principal;
    isApproved: boolean;
    name: string;
    joinedAt: Time;
    role: Role;
    organization?: string;
    phone: string;
    location: string;
}
export enum DeliveryStatus {
    onTheWay = "onTheWay",
    pickedUp = "pickedUp",
    delivered = "delivered",
    accepted = "accepted"
}
export enum Role {
    ngo = "ngo",
    admin = "admin",
    host = "host",
    volunteer = "volunteer"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_cancelled_fulfilled_open {
    cancelled = "cancelled",
    fulfilled = "fulfilled",
    open = "open"
}
export enum Variant_expired_completed_claimed_available {
    expired = "expired",
    completed = "completed",
    claimed = "claimed",
    available = "available"
}
export enum Variant_kg_pieces_litres {
    kg = "kg",
    pieces = "pieces",
    litres = "litres"
}
export enum Variant_low_high_critical_medium {
    low = "low",
    high = "high",
    critical = "critical",
    medium = "medium"
}
export enum Variant_veg_nonVeg {
    veg = "veg",
    nonVeg = "nonVeg"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptDelivery(listingId: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    cancelFoodRequest(requestId: bigint): Promise<void>;
    cancelListing(listingId: bigint): Promise<void>;
    claimListing(listingId: bigint): Promise<void>;
    createFoodRequest(request: FoodRequest): Promise<void>;
    createListing(listing: FoodListing): Promise<void>;
    createNotification(userId: Principal, message: string): Promise<void>;
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    getAllDeliveries(): Promise<Array<Delivery>>;
    getAllListings(): Promise<Array<FoodListing>>;
    getAllRequests(): Promise<Array<FoodRequest>>;
    getAvailableListings(limit: bigint, offset: bigint): Promise<Array<FoodListing>>;
    getAvailableTasks(): Promise<Array<FoodListing>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyDeliveries(): Promise<Array<Delivery>>;
    getMyListings(): Promise<Array<FoodListing>>;
    getMyNotifications(): Promise<Array<Notification>>;
    getMyRequests(): Promise<Array<FoodRequest>>;
    getOpenRequests(): Promise<Array<FoodRequest>>;
    getPlatformStats(): Promise<PlatformStats>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    listAllUsers(): Promise<Array<UserProfile>>;
    markNotificationAsRead(notificationId: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    toggleNgoApproval(ngoId: Principal): Promise<void>;
    updateDeliveryStatus(deliveryId: bigint, status: DeliveryStatus, proofImage: ExternalBlob | null): Promise<void>;
    updateListingStatus(listingId: bigint, status: Variant_expired_completed_claimed_available): Promise<void>;
}
import type { Delivery as _Delivery, DeliveryStatus as _DeliveryStatus, ExternalBlob as _ExternalBlob, FoodListing as _FoodListing, FoodRequest as _FoodRequest, Role as _Role, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptDelivery(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptDelivery(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptDelivery(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async cancelFoodRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelFoodRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelFoodRequest(arg0);
            return result;
        }
    }
    async cancelListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelListing(arg0);
            return result;
        }
    }
    async claimListing(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimListing(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimListing(arg0);
            return result;
        }
    }
    async createFoodRequest(arg0: FoodRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFoodRequest(to_candid_FoodRequest_n10(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFoodRequest(to_candid_FoodRequest_n10(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createListing(arg0: FoodListing): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createListing(to_candid_FoodListing_n15(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createListing(to_candid_FoodListing_n15(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createNotification(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createNotification(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createNotification(arg0, arg1);
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllDeliveries(): Promise<Array<Delivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllListings(): Promise<Array<FoodListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllListings();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllListings();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRequests(): Promise<Array<FoodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableListings(arg0: bigint, arg1: bigint): Promise<Array<FoodListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableListings(arg0, arg1);
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableListings(arg0, arg1);
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTasks(): Promise<Array<FoodListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTasks();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTasks();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyDeliveries(): Promise<Array<Delivery>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyDeliveries();
                return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyDeliveries();
            return from_candid_vec_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyListings(): Promise<Array<FoodListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyListings();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyListings();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyNotifications();
            return result;
        }
    }
    async getMyRequests(): Promise<Array<FoodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOpenRequests(): Promise<Array<FoodRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOpenRequests();
                return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOpenRequests();
            return from_candid_vec_n37(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlatformStats(): Promise<PlatformStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlatformStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlatformStats();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAllUsers();
                return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAllUsers();
            return from_candid_vec_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async markNotificationAsRead(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationAsRead(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n19(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async toggleNgoApproval(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleNgoApproval(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleNgoApproval(arg0);
            return result;
        }
    }
    async updateDeliveryStatus(arg0: bigint, arg1: DeliveryStatus, arg2: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n51(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n51(this._uploadFile, this._downloadFile, arg1), await to_candid_opt_n53(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async updateListingStatus(arg0: bigint, arg1: Variant_expired_completed_claimed_available): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateListingStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateListingStatus(arg0, to_candid_variant_n17(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_DeliveryStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryStatus): DeliveryStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_Delivery_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Delivery): Promise<Delivery> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_FoodListing_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodListing): FoodListing {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_FoodRequest_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FoodRequest): FoodRequest {
    return from_candid_record_n39(_uploadFile, _downloadFile, value);
}
function from_candid_Role_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Role): Role {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n49(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n29(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Principal]): Principal | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n43(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _DeliveryStatus;
    listingId: bigint;
    createdAt: _Time;
    updatedAt: _Time;
    volunteerId: Principal;
    ngoId: Principal;
    proofImage: [] | [_ExternalBlob];
}): Promise<{
    id: bigint;
    status: DeliveryStatus;
    listingId: bigint;
    createdAt: Time;
    updatedAt: Time;
    volunteerId: Principal;
    ngoId: Principal;
    proofImage?: ExternalBlob;
}> {
    return {
        id: value.id,
        status: from_candid_DeliveryStatus_n26(_uploadFile, _downloadFile, value.status),
        listingId: value.listingId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        volunteerId: value.volunteerId,
        ngoId: value.ngoId,
        proofImage: record_opt_to_undefined(await from_candid_opt_n28(_uploadFile, _downloadFile, value.proofImage))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        expired: null;
    } | {
        completed: null;
    } | {
        claimed: null;
    } | {
        available: null;
    };
    expiresAt: _Time;
    createdAt: _Time;
    unit: {
        kg: null;
    } | {
        pieces: null;
    } | {
        litres: null;
    };
    cookedAt: _Time;
    ngoId: [] | [Principal];
    notes: string;
    quantity: bigint;
    hostId: Principal;
    vegNonVeg: {
        veg: null;
    } | {
        nonVeg: null;
    };
    foodName: string;
    pickupLocation: string;
}): {
    id: bigint;
    status: Variant_expired_completed_claimed_available;
    expiresAt: Time;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    cookedAt: Time;
    ngoId?: Principal;
    notes: string;
    quantity: bigint;
    hostId: Principal;
    vegNonVeg: Variant_veg_nonVeg;
    foodName: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n33(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        unit: from_candid_variant_n34(_uploadFile, _downloadFile, value.unit),
        cookedAt: value.cookedAt,
        ngoId: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.ngoId)),
        notes: value.notes,
        quantity: value.quantity,
        hostId: value.hostId,
        vegNonVeg: from_candid_variant_n36(_uploadFile, _downloadFile, value.vegNonVeg),
        foodName: value.foodName,
        pickupLocation: value.pickupLocation
    };
}
function from_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        fulfilled: null;
    } | {
        open: null;
    };
    urgency: {
        low: null;
    } | {
        high: null;
    } | {
        critical: null;
    } | {
        medium: null;
    };
    createdAt: _Time;
    unit: {
        kg: null;
    } | {
        pieces: null;
    } | {
        litres: null;
    };
    numberOfPeople: bigint;
    ngoId: Principal;
    notes: string;
    quantityNeeded: bigint;
    foodType: string;
}): {
    id: bigint;
    status: Variant_cancelled_fulfilled_open;
    urgency: Variant_low_high_critical_medium;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    numberOfPeople: bigint;
    ngoId: Principal;
    notes: string;
    quantityNeeded: bigint;
    foodType: string;
} {
    return {
        id: value.id,
        status: from_candid_variant_n40(_uploadFile, _downloadFile, value.status),
        urgency: from_candid_variant_n41(_uploadFile, _downloadFile, value.urgency),
        createdAt: value.createdAt,
        unit: from_candid_variant_n34(_uploadFile, _downloadFile, value.unit),
        numberOfPeople: value.numberOfPeople,
        ngoId: value.ngoId,
        notes: value.notes,
        quantityNeeded: value.quantityNeeded,
        foodType: value.foodType
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    isApproved: boolean;
    name: string;
    joinedAt: _Time;
    role: _Role;
    organization: [] | [string];
    phone: string;
    location: string;
}): {
    id: Principal;
    isApproved: boolean;
    name: string;
    joinedAt: Time;
    role: Role;
    organization?: string;
    phone: string;
    location: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        name: value.name,
        joinedAt: value.joinedAt,
        role: from_candid_Role_n45(_uploadFile, _downloadFile, value.role),
        organization: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.organization)),
        phone: value.phone,
        location: value.location
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    onTheWay: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
}): DeliveryStatus {
    return "onTheWay" in value ? DeliveryStatus.onTheWay : "pickedUp" in value ? DeliveryStatus.pickedUp : "delivered" in value ? DeliveryStatus.delivered : "accepted" in value ? DeliveryStatus.accepted : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    expired: null;
} | {
    completed: null;
} | {
    claimed: null;
} | {
    available: null;
}): Variant_expired_completed_claimed_available {
    return "expired" in value ? Variant_expired_completed_claimed_available.expired : "completed" in value ? Variant_expired_completed_claimed_available.completed : "claimed" in value ? Variant_expired_completed_claimed_available.claimed : "available" in value ? Variant_expired_completed_claimed_available.available : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    kg: null;
} | {
    pieces: null;
} | {
    litres: null;
}): Variant_kg_pieces_litres {
    return "kg" in value ? Variant_kg_pieces_litres.kg : "pieces" in value ? Variant_kg_pieces_litres.pieces : "litres" in value ? Variant_kg_pieces_litres.litres : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    veg: null;
} | {
    nonVeg: null;
}): Variant_veg_nonVeg {
    return "veg" in value ? Variant_veg_nonVeg.veg : "nonVeg" in value ? Variant_veg_nonVeg.nonVeg : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    fulfilled: null;
} | {
    open: null;
}): Variant_cancelled_fulfilled_open {
    return "cancelled" in value ? Variant_cancelled_fulfilled_open.cancelled : "fulfilled" in value ? Variant_cancelled_fulfilled_open.fulfilled : "open" in value ? Variant_cancelled_fulfilled_open.open : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
}): Variant_low_high_critical_medium {
    return "low" in value ? Variant_low_high_critical_medium.low : "high" in value ? Variant_low_high_critical_medium.high : "critical" in value ? Variant_low_high_critical_medium.critical : "medium" in value ? Variant_low_high_critical_medium.medium : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ngo: null;
} | {
    admin: null;
} | {
    host: null;
} | {
    volunteer: null;
}): Role {
    return "ngo" in value ? Role.ngo : "admin" in value ? Role.admin : "host" in value ? Role.host : "volunteer" in value ? Role.volunteer : value;
}
function from_candid_variant_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Delivery>): Promise<Array<Delivery>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Delivery_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodListing>): Array<FoodListing> {
    return value.map((x)=>from_candid_FoodListing_n31(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FoodRequest>): Array<FoodRequest> {
    return value.map((x)=>from_candid_FoodRequest_n38(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n43(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): _DeliveryStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_FoodListing_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodListing): _FoodListing {
    return to_candid_record_n16(_uploadFile, _downloadFile, value);
}
function to_candid_FoodRequest_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FoodRequest): _FoodRequest {
    return to_candid_record_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Role_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): _Role {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n54(_uploadFile, _downloadFile, value));
}
function to_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_cancelled_fulfilled_open;
    urgency: Variant_low_high_critical_medium;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    numberOfPeople: bigint;
    ngoId: Principal;
    notes: string;
    quantityNeeded: bigint;
    foodType: string;
}): {
    id: bigint;
    status: {
        cancelled: null;
    } | {
        fulfilled: null;
    } | {
        open: null;
    };
    urgency: {
        low: null;
    } | {
        high: null;
    } | {
        critical: null;
    } | {
        medium: null;
    };
    createdAt: _Time;
    unit: {
        kg: null;
    } | {
        pieces: null;
    } | {
        litres: null;
    };
    numberOfPeople: bigint;
    ngoId: Principal;
    notes: string;
    quantityNeeded: bigint;
    foodType: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n12(_uploadFile, _downloadFile, value.status),
        urgency: to_candid_variant_n13(_uploadFile, _downloadFile, value.urgency),
        createdAt: value.createdAt,
        unit: to_candid_variant_n14(_uploadFile, _downloadFile, value.unit),
        numberOfPeople: value.numberOfPeople,
        ngoId: value.ngoId,
        notes: value.notes,
        quantityNeeded: value.quantityNeeded,
        foodType: value.foodType
    };
}
function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: Variant_expired_completed_claimed_available;
    expiresAt: Time;
    createdAt: Time;
    unit: Variant_kg_pieces_litres;
    cookedAt: Time;
    ngoId?: Principal;
    notes: string;
    quantity: bigint;
    hostId: Principal;
    vegNonVeg: Variant_veg_nonVeg;
    foodName: string;
    pickupLocation: string;
}): {
    id: bigint;
    status: {
        expired: null;
    } | {
        completed: null;
    } | {
        claimed: null;
    } | {
        available: null;
    };
    expiresAt: _Time;
    createdAt: _Time;
    unit: {
        kg: null;
    } | {
        pieces: null;
    } | {
        litres: null;
    };
    cookedAt: _Time;
    ngoId: [] | [Principal];
    notes: string;
    quantity: bigint;
    hostId: Principal;
    vegNonVeg: {
        veg: null;
    } | {
        nonVeg: null;
    };
    foodName: string;
    pickupLocation: string;
} {
    return {
        id: value.id,
        status: to_candid_variant_n17(_uploadFile, _downloadFile, value.status),
        expiresAt: value.expiresAt,
        createdAt: value.createdAt,
        unit: to_candid_variant_n14(_uploadFile, _downloadFile, value.unit),
        cookedAt: value.cookedAt,
        ngoId: value.ngoId ? candid_some(value.ngoId) : candid_none(),
        notes: value.notes,
        quantity: value.quantity,
        hostId: value.hostId,
        vegNonVeg: to_candid_variant_n18(_uploadFile, _downloadFile, value.vegNonVeg),
        foodName: value.foodName,
        pickupLocation: value.pickupLocation
    };
}
function to_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    isApproved: boolean;
    name: string;
    joinedAt: Time;
    role: Role;
    organization?: string;
    phone: string;
    location: string;
}): {
    id: Principal;
    isApproved: boolean;
    name: string;
    joinedAt: _Time;
    role: _Role;
    organization: [] | [string];
    phone: string;
    location: string;
} {
    return {
        id: value.id,
        isApproved: value.isApproved,
        name: value.name,
        joinedAt: value.joinedAt,
        role: to_candid_Role_n21(_uploadFile, _downloadFile, value.role),
        organization: value.organization ? candid_some(value.organization) : candid_none(),
        phone: value.phone,
        location: value.location
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_cancelled_fulfilled_open): {
    cancelled: null;
} | {
    fulfilled: null;
} | {
    open: null;
} {
    return value == Variant_cancelled_fulfilled_open.cancelled ? {
        cancelled: null
    } : value == Variant_cancelled_fulfilled_open.fulfilled ? {
        fulfilled: null
    } : value == Variant_cancelled_fulfilled_open.open ? {
        open: null
    } : value;
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_low_high_critical_medium): {
    low: null;
} | {
    high: null;
} | {
    critical: null;
} | {
    medium: null;
} {
    return value == Variant_low_high_critical_medium.low ? {
        low: null
    } : value == Variant_low_high_critical_medium.high ? {
        high: null
    } : value == Variant_low_high_critical_medium.critical ? {
        critical: null
    } : value == Variant_low_high_critical_medium.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_kg_pieces_litres): {
    kg: null;
} | {
    pieces: null;
} | {
    litres: null;
} {
    return value == Variant_kg_pieces_litres.kg ? {
        kg: null
    } : value == Variant_kg_pieces_litres.pieces ? {
        pieces: null
    } : value == Variant_kg_pieces_litres.litres ? {
        litres: null
    } : value;
}
function to_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_expired_completed_claimed_available): {
    expired: null;
} | {
    completed: null;
} | {
    claimed: null;
} | {
    available: null;
} {
    return value == Variant_expired_completed_claimed_available.expired ? {
        expired: null
    } : value == Variant_expired_completed_claimed_available.completed ? {
        completed: null
    } : value == Variant_expired_completed_claimed_available.claimed ? {
        claimed: null
    } : value == Variant_expired_completed_claimed_available.available ? {
        available: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_veg_nonVeg): {
    veg: null;
} | {
    nonVeg: null;
} {
    return value == Variant_veg_nonVeg.veg ? {
        veg: null
    } : value == Variant_veg_nonVeg.nonVeg ? {
        nonVeg: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Role): {
    ngo: null;
} | {
    admin: null;
} | {
    host: null;
} | {
    volunteer: null;
} {
    return value == Role.ngo ? {
        ngo: null
    } : value == Role.admin ? {
        admin: null
    } : value == Role.host ? {
        host: null
    } : value == Role.volunteer ? {
        volunteer: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): {
    onTheWay: null;
} | {
    pickedUp: null;
} | {
    delivered: null;
} | {
    accepted: null;
} {
    return value == DeliveryStatus.onTheWay ? {
        onTheWay: null
    } : value == DeliveryStatus.pickedUp ? {
        pickedUp: null
    } : value == DeliveryStatus.delivered ? {
        delivered: null
    } : value == DeliveryStatus.accepted ? {
        accepted: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
